### ISSUE TITLE
[proposal:question]

### ISSUE THREAD

**Issue by remotejob** [NaxAlpha/gpt-2xy#5]
I try  deploy gcr.io/innate-harbor-198712/gpt-2xy  on **google run** but all my tentatives was unsuccessful 
`Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.`

But container completely OK and run well on local PC.

As well my own created container on the base of yours project don't start, the same issue created.

Maybe sometime change in   **google run** environment ? 

It will nice if you try redeploy yours project. 

PS:
Scan log don't help at least for me.

**Comment by NaxAlpha** [comment]
Hi, there was an issue, I had built image with `GPT-2 345M` parameter model which does not run on cloud run so I fixed that, could you try again?

**Comment by remotejob** [comment]
I try redeploy but the same issue

`Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.`

Probably better incorporate gpt2 model in container instead of download

**Comment by NaxAlpha** [comment]
Yeah checked it, there was an issue with the docker build. Try this instead:
https://hub.docker.com/repository/docker/naxalpha/gpt-2xy
