### ISSUE TITLE
How to run this by using GPU ?

### ISSUE THREAD

**Issue by jiro412j** [NaxAlpha/gpt-2xy#6]
I already set up a server using CUDA and everything but I am not sure how to force it to run on 
GPU. It seems like it uses CPU every time even though I change from `torch cpu` to normal `torch`. Any help would be appreciated. Thank you in advance.

**Comment by NaxAlpha** [comment]
Sorry about that, since I built it only for CPU usage, code didn't care whether there is a GPU or not but I have updated the code to use GPU.

**Comment by jiro412j** [comment]
It works now. Thank you very much.
